config/routes.rb
Rails.application.routes.draw do
  root 'cars#index'
  get 'cars/ratings', to: 'cars#highest_rating'
  
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  resources :cars
  resources :cars, only: [:show] do
    resources :parts, only: [:show, :index, :new,:create, :destroy]
  end
  resources :parts
  # resources :vehicles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord

    # Has Many / Belongs To
    has_many :parts
    has_many :users, through: :parts
    belongs_to :user
    belongs_to :vehicle

    # Nested Attributes
    accepts_nested_attributes_for :parts, allow_destroy: true

    # Validations
    validates :make, length: {minimum: 1}
    validates :model, :presence => true
    validates :model, :presence => true
    validates :year, :presence => true
    validates :rating, :presence => true
    validates_inclusion_of :year, :in => 1900..2021
    validates_inclusion_of :rating, :in => 1..5


    # Scope Methods
    scope :good_car, ->{where("rating >= 4")}
    scope :good_new_cars, -> {new_car.where("rating >= 4")}
    scope :good_old_cars, -> {old_car.where("rating >= 4")}
    scope :best_cars, -> {car.where("rating >= 4")}
    scope :best_vans, -> {van.where("rating >= 4")}
    scope :best_trucks, -> {truck.where("rating >= 4")}
    scope :good_and_new, -> {new_car.where("rating >= 4")}

    # Class Methods
    def self.new_car
        where("year > 1996")
    end
    def self.old_car
        where("year < 1996 ")
    end
    def self.car
        where("vehicle_id == 1")
    end
    def self.van
        where("vehicle_id == 3")
    end
    def self.truck
        where("vehicle_id == 2")
    end

    # Display Vehicle Name
    def vehicle_name=(name)
        self.vehicle = Vehicle.find_or_create_by(name: name)
    end
        
    def vehicle_name
        self.vehicle ? self.vehicle.name : nil
    end

end

app/models/part.rb
class Part < ApplicationRecord
    
    # Has Many / Belongs To
    belongs_to :car
    belongs_to :user

    # Validations
    validates :name, :presence => true
    validates :rating, presence: true, numericality: { only_integer: true }
    validates_inclusion_of :rating, :in => 1..5

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable,
        :omniauthable, omniauth_providers: [:google_oauth2]
  
  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  # Has Many / Belongs To
  has_many :cars
  has_many :parted_cars, through: :parts
  has_many :parts
  has_many :vehicles, through: :cars

  # Validations
  validates :email, uniqueness: true

end

app/models/vehicle.rb
class Vehicle < ApplicationRecord

    # Has Many / Belongs To
    has_many :cars
    has_many :users, through: :cars

    # Validations
    validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?
    
    def logged_in?
        !!current_user
    end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show, :highest_rating]

    def index
        @cars = Car.all
        @new_cars = Car.new_car
        @old_cars = Car.old_car
        @trucks = Car.truck
        @cars_list = Car.car
        @vans = Car.van
    end

    def highest_rating
        @cars = Car.all
        @good_car = Car.good_car
        @good_new_cars = Car.good_new_cars
        @good_old_cars = Car.good_old_cars
        @best_cars = Car.best_cars
        @best_vans = Car.best_vans
        @best_trucks = Car.best_trucks
    end

    def new
        @car = Car.new
    end

    def create
        vehicle = Vehicle.find_or_create_by(name: params[:car][:vehicle_name])
        @car = current_user.cars.build(car_params)
        if @car.save
            redirect_to car_path(@car)
        else
            render :new
        end
    end

    def show
        @car = Car.find(params[:id])
        @part = @car.parts.build
    end

    def edit
        @car = Car.find(params[:id])
    end

    def update
        @car = Car.find(params[:id])
        @car.update(car_params)
        if @car.save
            redirect_to car_path(@car)
        else
            render :edit
        end
    end

    def destroy
        @car = Car.find(params[:id])
        @car.destroy
        flash[:notice] = "Car deleted."
        redirect_to root_path
    end

    def car_params
        params.require(:car).permit(:make,:model,:year, :vehicle_name, :rating, parts_attributes: [:id, :name])
    end
end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController

    def google_oauth2
        @user = User.create_from_provider_data(request.env['omniauth.auth'])
        if @user.persisted?
            sign_in_and_redirect @user
        else
            flash[:error] = 'There was a problem signing you in through Google. Please register or try signing in later.'
            redirect_to new_user_registration_url
        end
    end

    def failure
        flash[:error] = 'There was a problem signing you in. Please register or try signing in later.'
        redirect_to new_user_registration_url
    end


end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]

    def index
        if params[:car_id]
            @parts = Car.find(params[:car_id]).parts
        else
            @parts = Part.all
        end
    end

    def show
        @part = Part.find(params[:id])
    end

    def new
        if params[:car_id] && !Car.exists?(params[:car_id])
            redirect_to cars_path, alert: "Car not found."
        else
            @part = Part.new(car_id: params[:car_id])
        end
    end

    def create
        @part = current_user.parts.build(part_params)
        if @part.save
            redirect_to car_part_path(@part, @part)
        else
            flash.alert = "Fill out a valid ."
            render :new
        end
    end
    def edit
        if params[:car_id]
            car = Car.find_by(id: params[:car_id])
            if car.nil?
                redirect_to cars_path, alert: "Car not found."
            else
                @part = car.parts.find_by(id: params[:id])
                redirect_to car_parts_path(car), alert: "Part not found." if @part.nil?
            end
        else
            @part = Part.find(params[:id])
        end
    end

    def update
        @part = Part.find(params[:id])
        @part.update(part_params)
        if @part.save
            redirect_to part_path
        else
            render :edit
        end
    end

    def destroy
        @part = Part.find(params[:id])
        @part.destroy
        flash[:notice] = "Part deleted."
        redirect_to root_path
    end

    def part_params
        params.require(:part).permit(:name, :car_id, :user_id, :rating)
    end
end

app/controllers/vehicles_controller.rb
class  VehiclesController < ApplicationController
    before_action :authenticate_user!
    def index
        @vehicles = Vehicle.all
    end

    def new
        @vehicle = Vehicle.new
    end

    def create
        @vehicle = Vehicle.new(vehicle_params)
        if @vehicle.save
            redirect_to vehicles_path(@vehicle)
        else
            render :new
        end
    end

    def vehicle_params
        params.require(:vehicle).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/cars/_all_cars.html.erb
<% @cars.each do |car| %>
    <tr>
        <li><%= link_to car.make, car_path(car) %> | <%= car.year %> | <%= car.model %> | <%= car.rating  %> | <%= car.vehicle_name %></li>
    </tr>
<% end %><br>

app/views/cars/_best_cars.html.erb
<% @best_cars.each do |car| %>
    <tr>
        <li><%= link_to car.make, car_path(car) %> | <%= car.year %> | <%= car.model %> | <%= car.rating %></li>
    </tr>
<% end %>

app/views/cars/_best_trucks.html.erb
<% @best_trucks.each do |car| %>
    <tr>
        <li><%= link_to car.make, car_path(car) %> | <%= car.year %> | <%= car.model %> | <%= car.rating %> | <%= car.vehicle_name %></li>
    </tr>
<% end %>

app/views/cars/_cars_list.html.erb
<% @cars_list.each do |car| %>
    <tr>
        <li><%= link_to car.make, car_path(car) %> | <%= car.year %> | <%= car.model %> | <%= car.rating %> | <%= car.vehicle_name %></li>
    </tr>
<% end %>

app/views/cars/_good_new_cars.html.erb
<% @good_new_cars.each do |car| %>
    <tr>
        <li><%= link_to car.make, car_path(car) %> | <%= car.year %> | <%= car.model %> | <%= car.rating %></li>
    </tr>
<% end %>

app/views/cars/_good_old_cars.html.erb
<% @good_old_cars.each do |car| %>
    <tr>
        <li><%= link_to car.make, car_path(car) %> | <%= car.year %> | <%= car.model %> | <%= car.rating %></li>
    </tr>
<% end %>

app/views/cars/_old_cars.html.erb
<% @old_cars.each do |car| %>
    <tr>
        <li><%= link_to car.make, car_path(car) %> | <%= car.year %> | <%= car.model %> | <%= car.rating %> | <%= car.vehicle_name %></li>
    </tr>
<% end %>

app/views/cars/_part_amount.html.erb
<p>Number of Parts | <strong><%= pluralize(@car.parts.count,'Part') %></strong></p>

app/views/cars/_top.html.erb
<p>
    <strong>Model:</strong><%= @car.make %> 
    | <strong>Model:</strong><%= @car.model %> 
    | <strong>Rating:</strong><%= @car.rating %> 
    | <strong>Year:</strong><%= @car.year %>
</p>

app/views/cars/_vans.html.erb
<% @vans.each do |car| %>
    <tr>
        <li><%= link_to car.make, car_path(car) %> | <%= car.year %> | <%= car.model %> | <%= car.rating %> | <%= car.vehicle_name %></li>
    </tr>
<% end %>

app/views/cars/edit.html.erb
<h1>Edit Car</h1>
<%= render 'form' %>

app/views/cars/highest_rating.html.erb
<h1>Rankings</h1>

<h2>Good Car</h2>
<%= render 'good_car' %>

<h2>Good New Cars</h2>
<%= render 'good_new_cars' %>

<h2>Good Old Cars</h2>
<%= render 'good_old_cars' %>

<h2> Best Cars</h2>
<%= render 'best_cars' %>

<h2> Best_Vans </h2>
<%= render 'best_vans' %>

<h2>Best Trucks</h2>
<%= render 'best_trucks' %>

app/views/cars/index.html.erb
<%= link_to "See Car Ranking", cars_ratings_path %><br>

<h2>All Cars</h2>
<%= render 'all_cars' %>

<h2>New Cars</h2>
<%= render 'new_cars' %>

<h2>Old Cars</h2>
<%= render 'old_cars' %>
<br>

<h2>Car</h2>
<%= render 'cars_list' %>

<h2>Truck</h2>
<%= render 'trucks' %>

<h2>Van</h2>
<%= render 'vans' %>

app/views/cars/new.html.erb
<h1>Create a Car</h1>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nineteen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      
      <%= link_to "Home", root_path %>
      <% if !user_signed_in? %>
        <%= link_to "Sign Up", new_user_registration_path %>
        <%= link_to "Sign In", new_user_session_path %>
      <% end %><br>
      <% if user_signed_in? %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        <%= link_to "New Car", new_car_path %>
      <% end %><br>
      <% if logged_in? %>
        <%= "#{current_user.email}" %>
      <% end %><br>
    <%= yield %>
  </body>
</html>

app/views/parts/_buttons.html.erb
<%= link_to 'Back', car_parts_path(@part.car_id) %>
<% if current_user == @part.user %>
    <%= link_to 'Edit', edit_part_path(@part) %>
    <td><%= link_to 'Delete', part_path(@part),
            method: :delete,
            data: { confirm: 'Are you sure?' } %></td>
<% end %>

app/views/parts/_form.html.erb
<%= form_for [@car, @part] do |f| %>
    <% if @part.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@part.errors.count, "error") %>
                prohibited this post from being saved:
            </h2>

            <ul>
                <% @part.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "ex. Wheel" %><br>
    <br />
    <%= f.label :rating %>
    <%= f.number_field :rating, placeholder: "1-5 (lowest to highest)" %><br>
    <br />
    <%= f.hidden_field :car_id %>
    <%= f.hidden_field :user_id %>
    <%= f.submit %>
<% end %>

app/views/parts/_list_parts.html.erb
<% @parts.each do |part| %>
    <div>
        <h4><%= link_to part.name, part_path(part)%></h4>
    </div>
<% end %>

app/views/parts/_lone_part.html.erb
<%= form_for @part  do |f| %>
    <% if @part.errors.any? %>
        <div id="error_explanation">
            <h2>There were some errors:</h2>

            <ul>
                <% @part.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <br />
    <%= f.hidden_field :car_id %>
    <%= f.hidden_field :user_id %>
    <%= f.submit %>
<% end %>

app/views/parts/_part_info.html.erb
<h4><%= @part.car.make %> <%= @part.car.model %></h4>
<h4><%= @part.name %></h4>
<h4><%= @part.rating %></h4>

app/views/parts/edit.html.erb
<h1>Edit a Part</h1>
<%= render 'form' %>

app/views/parts/index.html.erb
<h3>Cars Parts</h3>
<%= render 'list_parts' %>

app/views/parts/new.html.erb
<h1>Add a Part</h1>
<%= render 'form' %>

app/views/parts/show.html.erb
<%= render 'part_info' %>
<%= render 'buttons' %>

app/views/vehicles/_add_a_vehicle.html.erb
<%= link_to 'Add a Vehicle', new_vehicle_path %>

app/views/vehicles/_list_vehicles.html.erb
<% @vehicles.each do |vehicle| %>
    <tr>
        <li><%= vehicle.name %></li>
    </tr>
<% end %>

app/views/vehicles/_new.html.erb
<%= form_for @vehicle  do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.submit %>
<% end %>

app/views/vehicles/_show.html.erb
<%= @vehicle.name %>

app/views/vehicles/index.html.erb
<h2>Vehicle Types</h2>
<%= render 'list_vehicles' %>
<%= render 'add_a_vehicle' %>

app/views/vehicles/new.html.erb
<%= render 'new' %>

app/views/vehicles/show.html.erb
<%= render 'show' %>